logging:
  level:
    org:
      springframework: INFO
    io:
      xmljim: INFO
    com:
      zaxxer: DEBUG
    root: ERROR
#spring.datasource.initialization-mode=always
spring:
  datasource:
    platform: h2
  jpa:
    defer-datasource-initialization: true
  application:
    name: starter
  output:
    ansi:
      enabled: ALWAYS
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
        show-details: always
